language: python
env:
  global:
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TGZ=helm-v2.4.1-linux-amd64.tar.gz
  - TARGET_REPO_URL=https://github.com/sitewhere/sitewhere.github.io.git
  - TARGET_BR=master
  - REPO_DIR=/home/travis/build/sitewhere/sitewhere-k8s
  - GH_URL=https://sitewhere.io/helm-charts
  - YAMLLINT_VERSION=1.8.1
  - secure: s6xy2omQv2PyXPAE5p7vxYgbKaZDLd+mXMAUz42zY6FAWvInLI9qxJ2ghPuuvvMe2Fwdrc9p+ubzfKB5fqpNrt8LctIrgXmEWkMI9kvZ/7L/e8GvSsXwglfE9OVLhMVIAWzhZlqClFVO1dKz5LEj+KnYlSqSRkkLkKvWIgmiX279eaU8FTksMQT6oFsD+VoEyj9vhNPBGedh+aXvdkE9hLEQJKD98pbszNKPeSau1H935N1ENCUjDyY5RPVZjp1eL1FkiklZ++ZvksBB4JlXbvDB9Af7zcvttdSZ4W0Ck/AplpGCszhbx/FJ9EdwEnA4cMVJjzL0FfTwHX5CJudM2R+o/kendsmFVP6PwrhXJwNPZzBLRylZcSzIvEhn8JWaDSZrY5OMGJGwT4pELVD1Qn+m5zxQ8O9VNkz4ftEt8+JAlTaeap46TeubBgTvdUWIdU+8zlhx/BZyhzuDNkvUrvNFclfAer6UPfnM5oFE0jgxdPop0XzLQPujAnwbeOilOywY9b4JLYg/zRb4T1Olh4AdxP87460m4SLkGSR1DcRcWnV/tqYo/EJIVLE7aMjuZajaWLEagUUpK/sVJcOLGbWpKlC0aHJRsrNPJcUOveyV6Ub6zMRWMpCFYFDrlfR3EDvh74jP9Tj8s+M2RPmWjnEhOVpW2mAWnW21ZpxeNZk=
install:
- wget -q ${HELM_URL}/${HELM_TGZ}
- tar xzfv ${HELM_TGZ}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
- sudo pip install yamllint=="${YAMLLINT_VERSION}"
script:
- |
  helm lint ${REPO_DIR}/charts/sitewhere
  if [ $? != 0 ]; then
    travis_terminate 1
  fi
- yamllint -c .yamllint.yml -s .travis.yml .yamllint.yml
- yamllint -c .yamllint.yml -s $(find . -type f -name "Chart.yaml")
- yamllint -c .yamllint.yml -s $(find . -type f -name "values.yaml")
after_success:
- |
  if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    # Temporary dir for storing new packaged charts and index files
    BUILD_DIR=$(mktemp -d)
    # Useful URLs
    REPO_URL=`git config remote.origin.url`
    SSH_REPO=${REPO_URL/https:\/\/github.com\//git@github.com:}
    SHA=`git rev-parse --verify HEAD`
    # Push temporary directory to the stack
    pushd $BUILD_DIR
    # Iterate over all charts are package them
    helm dep update ${REPO_DIR}/charts/sitewhere
    helm package ${REPO_DIR}/charts/sitewhere
    # Indexing of charts
    if [ -f index.yaml ]; then
     helm repo index --url ${GH_URL} --merge index.yaml .
    else
     helm repo index --url ${GH_URL} .
    fi
    # Pop temporary directory from the stack
    popd
    # List all the contents that we will push
    ls ${BUILD_DIR}
    # Clone repository and empty target branch
    git clone ${TARGET_REPO_URL} out
    cd out
    git checkout ${TARGET_BR} || git checkout --orphan ${TARGET_BR}
    cd ..
    rm -rf out/helm-charts/* || exit 0
    # Copying contents of BUILD_DIR to out folder
    cp $BUILD_DIR/* out/helm-charts/
    cd out
    # Deploy if there are some changes
    git diff --quiet
    if [ $? != 0 ]; then
     # Add all new files to staging phase and commit the changes
     git config user.name "Travis CI"
     git config user.email "travis@travis-ci.org"
     git add -A .
     git status
     git commit -m "Travis deploy ${SHA}"
     # We can push.
     git push ${SSH_REPO}
     git remote add origin-helm https://${GH_TOKEN}@github.com/sitewhere/sitewhere.github.io.git > /dev/null 2>&1
     git push --quiet --set-upstream origin-helm master
    fi
  fi
notifications:
  email: true
  slack:
    on_success: change
    on_failure: always
