# Default values for SiteWhere Database infrastructure components.
mongodb-replicaset:
  replicas: 3
  persistentVolume:
    storageClass: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    storage: 10Gi
cassandra:
  enabled: false
  persistence:
    storageClass: rook-ceph-block
    accessMode: ReadWriteOnce
    size: 10Gi
influxdb:
  enabled: false
  persistence:
    storageClass: rook-ceph-block
    accessMode: ReadWriteOnce
    size: 10Gi
