apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sitewhere-mongodump
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sitewhere-mongodump
            image: mongo
            command: ["mongodump", "--host", "sitewhere-mongodb", "--out", "/dump", "--verbose"]
            volumeMounts:
            - mountPath: "/dump"
              name: mongodump
          volumes:
          - name: mongodump
            persistentVolumeClaim:
              claimName: sitewhere-mongodump-pvc
          restartPolicy: Never
