apiVersion: batch/v1
kind: Job
metadata:
  name: sitewhere-mongodump
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: sitewhere-mongodump
        image: bitnami/mongodb
        command: ["mongodump", "--host", "icp-mongodb", "--password",  "password", "--out", "/dump", "--verbose"]
        volumeMounts:
        - mountPath: "/dump"
          name: mongodump
      volumes:
      - name: mongodump
        persistentVolumeClaim:
          claimName: sitewhere-mongodump
      restartPolicy: Never
  backoffLimit: 4